databases:
  - name: deploy
    databaseName: deploy
    user: deploy
    plan: free

services:
  - type: web
    name: deploy
    env: ruby
    plan: free
    autoDeploy: false
    buildCommand: "./bin/render_build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: deploy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false